### ISSUE TITLE
textExercise "My Answer" input

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#10]
Previously, I asked if the "My Answer" line could be removed from the Notebook, as I would never write such a thing in a research notebook. Christian made the good point that we need some indicator of player-generated input (as distinguished from automatic input). Can we therefore change the line from "My Answer" to "My Input"? (This makes the notebook less like an exercise book, with questions and answers, and more like a place where the player is thinking and writing.)

**Comment by christian-bernet** [comment]
yes of course. Let's change that to "My Input".

**Comment by christian-bernet** [comment]
done
