### ISSUE TITLE
News and twitter feed on main page

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#100]
It seems like we'd benefit from two dynamic content spots on our welcome page: most recent news item, plus most recent tweet. Then there could be a news tab, which is an archive of all news (perhaps done with RSS?)

I'm sure this is very common task, but I personally haven't done it before, so don't know how long it will take to set up. But yeah, I think that's the best way for us to keep users in the loop.

Probably this should happen after our current milestone is passed, and be pair-programmed in by me and @witlox. With any luck there is some drop-in code already out there we can use.

**Comment by martindusinberre** [comment]
Thanks, that would be wonderful if you could develop this feature.

**Comment by interrogator** [comment]
OK it should be trivial to hook up the twitter feed. On top of that, I think we make a news tab, and any stories longer than a tweet we can add in there, and the tweet can link to them.

Here shows how super easy it will be:

https://developer.twitter.com/en/docs/twitter-for-websites/overview

**Comment by martindusinberre** [comment]
Great, good news. Thanks, Danny

**Comment by interrogator** [comment]
Awaiting comment from @lfeine regarding legality of the embedded tweet idea.

**Comment by martindusinberre** [comment]
@interrogator @witlox @lfeine As discussed on rocketchat today, the Twitter feed means that a social media site is embedded on our frontpage, which goes against our Data use agreement as it's currently formulated. For the demo, therefore, we don't implement this, and we perhaps revisit it before full launch. For this reason, I'm closing this issue but adding a reopenable label.
