### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#102]
@interrogator 

- [x] Change the time stamp settings in "Your games". This is because when I exited a game halfway through just now, "Open Games" recorded my unfinished game as being played on 7 December, not 7 November!

- [x] For the time stamp in the Notebook, can we set it to Central European Time? At the moment it's on Greenwich Mean Time. Not a major problem if it's a lot of work, though.

_Originally posted by @martindusinberre in https://github.com/uzh/marugoto/issues/90#issuecomment-551244852_

**Comment by interrogator** [comment]
lol, I think the problematic code is:

```js
  data: function() {
    return {
      months: ['January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', ' September', 'October', 'December'],
    };
  },
```

**Comment by interrogator** [comment]
First fix: https://github.com/uzh/marugoto-frontend/commit/ab0dcc1914f28f46e4167c66efbd81464cd9c421

**Comment by interrogator** [comment]
The other fix is going to be harder: frontend is apparently receiving UTC time for `createdAt`, which is good because that way localisation can be handled in the frontend (i.e. different times displayed for different users in different locations). However the frontend is not set up to convert times from UTC to local, and this will take some doing.

**Comment by interrogator** [comment]
Probably we can use: https://www.npmjs.com/package/vue-moment

**Comment by martindusinberre** [comment]
@interrogator OK, not a priority for the demo if it's terribly time consuming.

**Comment by interrogator** [comment]
We are trying to do it now

**Comment by interrogator** [comment]
These are both done, with added bonuses:

* Get correct time Your games, rather than just date
* Get day of the week something was done on
* Get localisation: people in other timezones will have their local time displayed.

Note that there may be other datelike things that need converting. @martindusinberre please let me know if you discover them, and we can apply this fix.
