### ISSUE TITLE
Styling Your Games like Welcome page

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#103]
Moved over from minor thread because it wouldn't be minor --- I still think it might be nice (some day) for the Your Games style to more closely resemble the homepage, perhaps with the map background and so on. This will help people understand the 'logged in vs logged out' home page better. @martindusinberre let me know if you want, and what prio it should be.

**Comment by martindusinberre** [comment]
@interrogator yes, if it's fairly easy to do the map as a background, and to style the page closer to the log-in page, great. I don't think it's probably necessary for the demo but something to do between now and the spring? Unless you can do it easily and would for aesthetic reasons prefer to have it done before we make the demo live. I leave it to you.

**Comment by martindusinberre** [comment]
@christian-bernet As discussed on Monday, please take a look at this. We'd be glad if the "Your Games" page could be styled a bit like the Welcome page, ie perhaps with the map as a background at some point? If you could, please send us a quick screenshot of what the new design looks like before you deploy the changes, just in case we have any comments/additions. Thanks, Martin

**Comment by christian-bernet** [comment]
@martindusinberre We would only do the design. The development has to be done from Daniel or Pim. Just let me know if this is possible and we will send you the new design.

**Comment by martindusinberre** [comment]
@witlox @interrogator does this work for you? For me, the redesign of the Your Games page isn't a priority, given that your working time is also limited. Shall we ask Vitamin2 to design it anyway, and then at least we have the design on file for future implementation in the new year or after full launch?

**Comment by interrogator** [comment]
Yes, I think design-wise it is logical that there is a bit more cohesion between these non-game screens. If there was a design, I could implement by full launch. @christian-bernet please add design details here

**Comment by christian-bernet** [comment]
Ok. I will see, that we can do a design for the "your game screen".

**Comment by christian-bernet** [comment]
![First Contact – LiT Login Copy 2@2x](https://user-images.githubusercontent.com/41006947/71364870-ac5b9e00-259d-11ea-874c-c9c7181d68ef.png)

This is our proposal for styling the "Your game Screen".

**Comment by christian-bernet** [comment]
If you want some changes or want the sketch file, just let me know.....

**Comment by martindusinberre** [comment]
@christian-bernet many thanks indeed for this! I like the look of it. @interrogator I don't think this is a priority for January, especially given the work percentages you're on, but perhaps we could see if you have spare capacity in February or March for it?
