### ISSUE TITLE
Minor thread 2 🤘📝🤘

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#104]
Anyone can add small issues to this thread. Use checkboxes for small issues such as typos, formatting, basic style stuff. Make independent issues for anything complicated.

* [ ] Check whether `underlined` class can be replaced by `link` class and deleted?
* [ ] Twitter/GitHub icons
* [ ] ...

**Comment by interrogator** [comment]
* [ ] All headers on main pages should be be same size and location

**Comment by martindusinberre** [comment]
- [ ] On the "Partners" tab on front page, please add "the" to the very first line: "...has been supported by the Swiss National..."

- [ ] In the Data Agreement, section 2 ("Collecting, Storing and Processing"), about halfway in, there's a sentence beginning, "We process this information in order for the game to react to your 'character' in the correct context." Please change the quotation marks around "character" to double-quotation marks.

**Comment by martindusinberre** [comment]
- [ ] In issue #97 , it seems like the edits I made to @witlox 's questions haven't been activated in some cases. E.g. "What colour does the sun have", which I deleted. *This isn't urgent*, as long as the captcha questions don't have any minor bug, as the "Other question" functionality works nicely. But if it's easy to delete that question, please do so. (The reason is that Japanese people might answer "red", while others might answer "yellow" or "orange". Also "what colour does x have" is a bit unnatural.)

**Comment by interrogator** [comment]
Regarding captcha, I agree that wording of some questions is not standard English and could be changed, and also that questions can be somewhat ambiguous. But @martindusinberre so you understand, most of this was intended, as these ambiguities, original lack of question mark etc, are what makes the questions hard for a machine to solve. Now that the human can click to get a new captcha, I think the system basically works as intended.

Perhaps there are types of questions that can serve this function while being culturally universal, but questions like 'What country is Sydney in?' are definitely not it, as computers can 'know' these kinds of things easily.

So with that out of the way, I suggest you/anyone else simply edit this file as you see fit, you can do it directly from the browser: https://github.com/witlox/acrion/blob/master/data.js . The format is basically JSON. Whatever question/answer pairs are in there when it is time to do an update will make it into the update, simple as that :)
