### ISSUE TITLE
Deployment resource names

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#105]
Currently, different topics cannot share a resource name, because they all end up in `resources/` directory. For example, two topics cannot have a `main.jpg`, because they will override each other during import time. This is not a good design and will need to be fixed.

@martindusinberre, for now, be sure to give all your resources unique names (even across topics)! Unassign yourself when you have internalised this.

@witlox and @interrogator will try to figure out the best fix, but it's not needed right now.

**Comment by interrogator** [comment]
While we have a known amount of game developers, it's OK to just make sure filenames are unique. I expect that by the time this really becomes an issue, we may have switched out the backend anyway. Time will tell.

**Comment by nemtish** [comment]
should be fixed now with 9815f12

**Comment by interrogator** [comment]
Thanks @nemtish , I can close this for now. The result is, resource file names now no longer need to be unique across games. This is important in case the game grows; we want to minimise problems that are caused by other (potentially unknown) people's content. Great job!
