### ISSUE TITLE
Autodeploy of test system broken?

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#107]
I have a feeling that our live system work broke the autodeploy of test system. We'll need to fix this soon, but it's not super urgent since we just went live yesterday.

**Comment by martindusinberre** [comment]
@interrogator Yes, this is definitely not working: the (small) changes I pushed to lit-demo haven't yet appeared in the frontend on the test system.

**Comment by interrogator** [comment]
I believe it's now working, and is using github.com/uzh/lit-content to fetch data. This means that adding new topics is quite trivial in future!
