### ISSUE TITLE
"Download" button perhaps not working on "Your Games" page?

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#108]
Can anyone reproduce this problem? I played Defining Work yesterday (13Nov) on the production system without any trouble. Today, when I logged in again, I went to "Finished games" but when I tried to click on "Download" to get my notebook from yesterday, nothing happened. 
As @lfeine has noted: it works fine if you download the PDF from the download icon in the Notebook, either during the game or on the final page; and it worked fine for her now from "Your games". But I have just played the demo again the downloads are not working from "Your games" for me, either for the game I played yesterday or for the one I played just now.

**Comment by christian-bernet** [comment]
@interrogator if you want, I can have a look at it next week.
All best, Christian

**Comment by interrogator** [comment]
Could be my issue, as I changed these buttons recently. I will look into it.

**Comment by interrogator** [comment]
I will reassign @christian-bernet if it was nothing to do with my frontend changes.

**Comment by interrogator** [comment]
I took a look at this this morning, and can't see anyway my small frontend changes would have much to do with it. So I'll let @christian-bernet have a go.

**Comment by martindusinberre** [comment]
@christian-bernet Following a meeting yesterday of the UZH team, we're going to aim to do an update to the production system next Monday or Tuesday, just to test what happens when we try to do so. Therefore, if you're able to look at this bug before midday on Monday 25th, that would be perfect; if not, then please see what you can do later in the week and we'll add the bug fix to the next update we do later in December.

**Comment by christian-bernet** [comment]
@interrogator can you send me the catalina log of the production machine, when you click on the download link at the production. I will be sure the java stack trace will help us to fix that.
Many thanks.

**Comment by interrogator** [comment]
Logs emailed, not posted here, in case sensitive info in them

**Comment by christian-bernet** [comment]
Thanks for the logs.
The temp folder is not correctly set on production.
Can you please set a folder where the tomcat has access to write files.

As out of the log this value 
marugoto.resource.temp.dir

**Comment by interrogator** [comment]
OK, we will do this
