### ISSUE TITLE
Clarify length of demo

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#111]
People are confused about demo being a demo because of 'Chapter 1/5'. Clarify

**Comment by martindusinberre** [comment]
@interrogator In the "Select a topic" page, please add these sentences *after* the sentence "The topic is called Defining Work":
"You can play the first of what will eventually be five chapters in this topic. The demo play time is about 15 minutes."
You might want to then make a line break between this and the sentence beginning "We are pleased...", but I leave it to you.
Thanks, M

**Comment by interrogator** [comment]
Done in https://github.com/uzh/marugoto-frontend/commit/4a795c80d7c6aad133047b060adef5a0c7d99549
