### ISSUE TITLE
"Official" documentation

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#114]
Can we please make some decisions regarding the documentation for game writers? Currently, we have the wonderful lit-tutorial game. I think that's awesome, but it is not very 'systematic', a game writer will want to be able to search docs for a string like "caption" to get clarification about what it does. So, in addition to the tutorial, should there be a writers' guide? @martindusinberre

I propose the use of mkdocs and readthedocs, which allows you to write markdown and which ends up rendering very nicely. Here is a project of mine that uses such a system: https://buzz.readthedocs.io/en/latest/ . This is basically using all system defaults, I can configure all this in 30 mins, it's really trivial to set up and free.

Documentation is basically a series of markdown files (e.g. https://github.com/interrogator/buzz/blob/master/docs/corpus.md) plus a tiny bit of code to hook it together, which is boilerplate (e.g. https://github.com/interrogator/buzz/blob/master/mkdocs.yml). You just add an entry to table of contents, write markdown, and push. When the docs are changed, readthedocs will update automatically.

I would like to set that up for this repository, and the lives in transit website can have a link somewhere to the "writers' guide", as well as the tutorial. This repo seems like the best place to store the docs, there is definitely no need to make yet another repository just for docs, or anything like that.

@martindusinberre do you want me to set it up? I create the very basics of it, and you just write markdown content as you like, whenever you push the website will update. It would look exactly like the buzz example above (there is some ability to customise the look and feel but I don't think it matters right now). Just tell me what I should name it (e.g. marugoto guide, lives in transit writers' guide, etc etc) and I can put all the infrastructure in place. @henokemp is getting invited too.

**Comment by martindusinberre** [comment]
@interrogator This sounds great! Yes, please set it up if you could, and I can then start migrating some of the generic advice I gave to @henokemp in his own project onto these pages. You can both add too, or simply questions/reminders where you think there are obvious gaps.
Why don't you name it "Lives in Transit Writers' Guide". Or, if you want something snappier, "LiT DIY".

**Comment by interrogator** [comment]
Reflecting on this, it's now set up and all people involved know how to add content. Since there is no point at which content is complete, I'm closing this issue. Please make a specific new issue if you want (e.g.) a whole new section or something like that. Also if something you don't understand about the site, make an issue, reopen this, whatever ...

DOCS: https://lives-in-transit.readthedocs.io/en/latest/
