### ISSUE TITLE
Minor issues to be fixed before launch if possible

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#117]
- [ ] - On the "Your Games" page, is it possible to have the time stamp for each of the "Open Games" **not** the time that you started the game, but rather the time you last exited the game? (This is less of a priority than the Notebook issue...)

- [x] In the Notebook (online), there's a bit of coding left over right after the date/time stamp for an entry (that is, `DD.MM.YYYY - HH:mm`). Can this be deleted? This has also become an issue in the trailer (Defining Lives), although it wasn't when we launched back in November. Occurred when I was using both Safari and Firefox browsers. Please note that everything with the date/time stamp entry works perfectly when you download the Notebook as a PDF at the end of the game.

**Comment by martindusinberre** [comment]
- [ ] Martin to delete PL shortcuts before launch

- [ ] Update frontpage and Game Selection page texts (MD to draft, including @henokemp's game, how to cite the different games, idea of writing a game as a student assignment, Tutorial game, writers' guide)

**Comment by martindusinberre** [comment]
- [ ] Create a buffer space in Topic Selection page so that the folder/photo graphic doesn't hide the text. And so that there's enough space for five folders, eventually. (Four only necessary now)

**Comment by martindusinberre** [comment]
- [ ] Is there anything that can be done about the line break that appears both before and after the monospace font (`page.json`) in the "Tutorial" game?

**Comment by interrogator** [comment]
Regarding the timer using the exited time, it is non-trivial, at least for me to implement, because it is pretty hard to know when the player closes tab with the game in it. I believe this should become an issue for next cycle.

**Comment by martindusinberre** [comment]
good, thanks for explaining about the exited time issue. That's all fine.
