### ISSUE TITLE
Email inbox - on left side show only mailForm and subject, remove mail body part

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#12]

**Comment by christian-bernet** [comment]
done

**Comment by martindusinberre** [comment]
This is now closed (at least until I can see the new version) but we are having problems closing it...

**Comment by christian-bernet** [comment]
ok. I can close it. I have written to Pim, so that he can change the rights.

**Comment by interrogator** [comment]
Can we comment the commit / PR before closing? Sorry, it's just I'd like to learn more about the codebase, and so it's really useful if I can see where changes need to be made for various parts...

**Comment by christian-bernet** [comment]
what do you mean with comment the commit?
The comment of the commit is for that change: "Remove body from mail list items"

**Comment by interrogator** [comment]
I mean, like if closing an issue, the code should now be in a branch, or in master. The commit that added the code should have a hash, which can be linked here so we can quickly see which commit solved the issue.

For example, I just paste the last commit on master here: 3d5559d, and github links it all automatically. This way, it's easy to get from an issue to its actual fix in the code.

**Comment by interrogator** [comment]
Definitely it's helpful that the commit message references the issue, but doing this as well makes it much more structured, and only takes a second.

**Comment by christian-bernet** [comment]
for frontend changes this won't work. it is commit ae0aae6 on dev branch in frontend....
But for backend changes we can do that.

**Comment by interrogator** [comment]
@christian-bernet, try:

`uzh/marugoto-frontend@ae0aae6`: uzh/marugoto-frontend@ae0aae6

**Comment by christian-bernet** [comment]
thanks
