### ISSUE TITLE
Changes to the LiT frontpage

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#121]
- [x] **Partners** tab: _Please change the second paragraph to:_
...…during development has been: Martin Dusinberre, Helena Jaskov, [Leyla Feiner](https://merveilles.town/@toadheart) and [Henrik Jochum](https://twitter.com/HJ_1812_0) (UZH Department of History), Pim… [_as is_]

- [x] **Citing LiT** tab: _For the list of authors on the second line, please add Henrik_:
Martin Dusinberre, Helena Jaskov, Daniel McDonald, Pim Witlox, Leyla Feiner and Henrik Jochum (2020): “Lives in Transit” [_… as is_]
*Then, directly below that:*
The current topics (June 2020) were authored as follows:
Martin Dusinberre et al, “Plantation Lives”
Martin Dusinberre et al, “Defining Work”
Henrik Jochum et al, “Feeling the Past”
Henrik Jochum, Leyla Feiner and Martin Dusinberre, “Tutorial”
For citing of a specific topic, we suggest:
[topic author et al ], [ topic title ], in Martin Dusinberre, Helena Jaskov, Daniel McDonald, Pim Witlox, Leyla Feiner and Henrik Jochum (2020): "Lives [_as is..._]
For example:
Dusinberre, Martin et al, “Plantation Lives”, in Martin Dusinberre, Helena Jaskov, Daniel McDonald, Pim Witlox, Leyla Feiner and Henrik Jochum (2020): “Lives in Transit” [_…as is_]
Or, if you prefer .bib format
author = "{Martin Dusinberre and Helena Jaskov and Daniel McDonald and Pim Witlox and Leyla Feiner and Henrik Jochum}", 
[_…as is_]

- [x] **About** tab (1)
Please add a hyperlink to [Marugoto](https://github.com/uzh/marugoto) on the first line.
_Please rewrite the Bug bounty programme paragraph as:_
Lives in Transit has been a major collaborative effort, including the core team at the University of Zurich (see “Partners” tab) and multiple testers and interlocutors. We hope to continue that work ethic after launch. In particular, to encourage feedback and the reporting of bugs, we've decided to run a Bug Bounty Programme, which rewards those who inform us of, or fix, some problem with either the game engine or game content. All those who inform us of bugs will be named (if they wish) in LiT’s “About” page under a new heading, “Bug Bounty Team”; those who go so far as to fix a bug (by way of a GitHub pull request) will be listed as a contributor to the project. 

- [x] **About** tab (2). _Please rewrite the "Creating your own content" paragraph as follows:_
One of our aims in the Lives in Transit project has been to make a tool which can be used not just for educational playing purposes, but also to encourage new forms of history writing. One of the game storylines in our 2020 launch, [“Feeling the Past”](https://github.com/henokemp/lit-feelingthepast), is indeed a student-written game, submitted by Henrik Jochum for one of his [MA History of the Contemporary World/Zeitgeschichte](https://www.hist.uzh.ch/de/studium/masterstudium/studienprogramme/MA-Zeitgeschichte/MA-History-of-the-Contemporary-World.html) classes at the University of Zurich. We similarly encourage university colleagues and students to consider developing their own content for Lives in Transit, or simply as class assignments. To do so, you can write JSON files that Marugoto can import and serve to Lives in Transit. A first step would be to play the game called “Tutorial”, and also refer to our [LiT writers’ guide](https://lives-in-transit.readthedocs.io/en/latest/) (currently under development). Further to that, please be in contact with us by email (globalhistory[at]hist[dot]uzh[dot]ch) if you'd like to create your own content. We’d be delighted to talk with you about how we could work together.

**Comment by interrogator** [comment]
All done

**Comment by martindusinberre** [comment]
thank you!
