### ISSUE TITLE
First minor updates to live system

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#124]
I've divided these issues into "fixes" and "improvements". Fixes are **high priority**:

**Fixes**
- [ ] A bug has emerged since deployment (it did not appear before 2 June), namely: in the downloadable PDF of the Notebook, images are no longer being displayed, neither under the correct Notebook entry nor in the Appendix at the end. This is true of all the games (except the Trailer "Defining Work", which deliberately wasn't updated), and it's true regardless of the browser. I suspect the bug may have been triggered by the fix @interrogator made to solve the date/time stamp code. Could it be debugged so that the images appear in the downloadable PDF of the Notebook again? Or, if the new fix is too much work, could the date/time stamp fix be reverted? That tiny bit of code being visible is less of a problem than the Notebook PDF not showing the images.

Edit by @interrogator ... for the record, I do not think this is related to the change to date time, but instead to the resources directory path change by @nemtish ... could be wrong, but that just makes more sense to me right now

- [x] Change layout of "Select a topic" page so that the four folders hang to the bottom of the page and don't cover the text

- [x] Change the button text on the game folders (in "Select a topic") from "Preview this topic" to "Play"

- [x] Please reimport and deploy Plantation Lives, Feeling the Past, Demo ("Defining Work") and Tutorial.

**Improvements (desirable but not essential if time is short)**
- [x] Merge the two pull requests from @lfeine for minor frontend changes: (i) to add a sentence to the "Your games" page, to explain more about the workflow for supervising a class, and (ii) to change the player icon when the teacher is seeing how many students in their class are playing their game. Pull request here: https://github.com/uzh/marugoto-frontend/pulls

**Comment by martindusinberre** [comment]
@interrogator  concerning the Notebook bug: here's an example from the test environment, played early on 3 June (ie a couple of hours before we went live), in which the Notebook displays both the images at the right Notebook entries and also in the Appendix at the end. This is the correct version.
[Martin Dusinberre-8.pdf](https://github.com/uzh/marugoto/files/4747552/Martin.Dusinberre-8.pdf)

**Comment by martindusinberre** [comment]
And here's the **incorrect** version, from the live system on 5 June, playing more or less the same game combination. Here you can see the PDF simply has the image captions but not the images themselves--neither on the correct page of the Notebook, nor in the Appendix.
[Martin  Dustinberry (2).pdf](https://github.com/uzh/marugoto/files/4747561/Martin.Dustinberry.2.pdf)

**Comment by interrogator** [comment]
My guess is that the images are not found since the resources path moved (now every game has own resources dir). My guess is that this part of the code was not updated to reflect that change. Will look into it.

**Comment by martindusinberre** [comment]
Many thanks for doing all this, @interrogator
