### ISSUE TITLE
Page transitions in HMCS storylines not working

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#14]
On 2.4.3.1.2.2 (and presumably also 2.4.4.1.2.2 and 2.4.5.1.2.2), I am unable to transition to the next page (2.4.3.1.2.3 etc). This seems to be a problem with the button text not appearing even though I have entered the correct numbers in the dateExercises. Can you check what the problem is?

**Comment by christian-bernet** [comment]
Bug is with multiple dateFields on one page.
- Input is not submitted only if field is changed
- Input is only on the last element submitted

**Comment by christian-bernet** [comment]
please check it at page333 of demoTopic

**Comment by martindusinberre** [comment]
This isn't working in page333 if the button "return to the library" is meant to appear when I've correctly inputted the dates: at the moment, the pageTransition button doesn't appear.

**Comment by christian-bernet** [comment]
this is done: uzh/marugoto-frontend@4779e09

**Comment by martindusinberre** [comment]
Great. Do I pull it into git? I'm not seeing it when I try to fetch at the moment.

**Comment by christian-bernet** [comment]
there was no change at the content. It was a bug in the frontend. so it will work now, without any change from your side.

**Comment by martindusinberre** [comment]
Sorted, thank you!
