### ISSUE TITLE
Page transition not working 2.4.5.1.7xx

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#15]
The page transition from 2.4.5.1.7.1 to 2.4.5.1.7.2 is slow. Then the page transition from 2.4.5.1.7.2 to 2.4.5.1.7.3. doesn't work at all--it just crashed out and took me to the log-in page again. When I logged in again, however, and went to "Continue" my game, I got back to 2.4.5.1.7.3 just fine.

**Comment by christian-bernet** [comment]
I think this was a temporary problem. slow and then the crashing. At least on my machine it is working.
but lets check that again, if the import is working again

**Comment by martindusinberre** [comment]
OK, great, I'll check it later. Thanks, Martin

**Comment by christian-bernet** [comment]
That is ok. Temporary problem (because of importer running or whatever).
