### ISSUE TITLE
Notebook display: when images with multiple pages save to Notebook, they display only first page

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#17]
This is a problem, for example, with the image that is saved from 2.4.1.3.1.5 to notebook.

**Comment by christian-bernet** [comment]
should we add each image or should we add the functionality to switch to the next image?

**Comment by christian-bernet** [comment]
Estimate 4 hours

**Comment by martindusinberre** [comment]
This is also connected to #38 in terms of images with multiple pages being displayed in the notebook's appendix when it's downloaded as a PDF

**Comment by martindusinberre** [comment]
This is now solved, thanks!
