### ISSUE TITLE
notVisited: work around solution for notVisited *or* notVisited

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#18]
But there's now still a problem in terms of notVisited when there are more than one inputs.
For example, I played chapter 4 visiting the Edersons first (2.4.1.3.4.1Ed).
When I got to 2.4.2.2, I was no longer offered the Edersons because the visitedAny functionality now works fine. Thanks!
But then, having played through HSA (2.4.3.1.1.1HSA) and come to 2.4.3.2, I was mistakenly offered the option of "Emi and Al Ederson". I had set this as follows:
notVisited 2.4.1.3.4.1Ed and notVisited 2.4.3.1.4.1Ed
In other words, I thought that players would only be offered the Ederson option if they had not visited the two previous Ederson pages.
Have I set this up wrongly? Perhaps I mean they should not be offered the Ederson option if they have notVisited either 2.4.1.3.4.1Ed or 2.4.3.1.4.1Ed.
I think we don't have the notVisitedAny functionality, so is there a workaround to this?

The combination of notVisited is also a problem at 2.4.4.1.3.3, for example, when the player sees two "Continue" buttons (they should only see one).

**Comment by christian-bernet** [comment]
so it is developed: commit f28a648d

@martindusinberre you will find an example in DemoTopic
