### ISSUE TITLE
App freeze when dialog skipped

### ISSUE THREAD

**Issue by zlaxi** [uzh/marugoto#19]
App freeze when dialog timer fires after page transition

**Comment by zlaxi** [comment]
Fix on master branch in commit:
https://github.com/uzh/marugoto-frontend/commit/bb7213500b2d8bd5b47b150a4d3d89345c9674dc

**Comment by christian-bernet** [comment]
ch4 decent money then continue until page Making a plan
choose Hamilton Library
on page Hamilton Library Round-Up click fast on the continue button
now the page is locked

**Comment by christian-bernet** [comment]
prefect
