### ISSUE TITLE
Fix error for coverage reporting

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#20]
Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project parent: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report failed: A required class was missing while executing org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter

In the backend....

**Comment by christian-bernet** [comment]
Estimate 1 hour

**Comment by interrogator** [comment]
Apparently not done and not handed over, so closing. Not a big problem anyway.
