### ISSUE TITLE
multiple date field on one page page transition stays

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#22]
it is in plantation lives on page 2.4.3.1.2.2. If you once put in the right dates the page transition is shown and never gone away. I think it's a backend bug.

**Comment by martindusinberre** [comment]
OK, the work-around for the test will be for me to change the page transition criteria (no longer need exact answer). Thanks, Martin

**Comment by christian-bernet** [comment]
you don't have to change anything. that is only a small issue. You can play through now.

**Comment by christian-bernet** [comment]
Estimate 1 hour

**Comment by nemtish** [comment]
Fix: https://github.com/uzh/marugoto/commit/6e62605ab627a8ee1ed2286ec33f3c2dbb437c16

**Comment by christian-bernet** [comment]
Reviewed and testet. Perfect.

**Comment by christian-bernet** [comment]
would you like to verify it? If not, simply close it.
