### ISSUE TITLE
Session management when internet dies

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#24]
During our testing, we had some internet connectivity issues. I found that basically any disruption in internet would send me back to the login screen, while other websites I have logins for remember me without issue. So I guess some session data storage with good timeouts could solve this.

**Comment by christian-bernet** [comment]
This is the last open task on our old jira board.
For Zlakto: it is https://vitamin2.atlassian.net/browse/UZHFE-180
Estimate: 4 houres

**Comment by interrogator** [comment]
Priority? This was a pretty constant problem for me when playing during the testing...

**Comment by christian-bernet** [comment]
to do now:

add loading bar 5 pixel black

Add dialog box if backend does not respond in the timeout! Instead of logging out! But log out afterwards!

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/95030d99f3959a4008185196dad3fdd0304b21a0

**Comment by christian-bernet** [comment]
ok. now.

**Comment by martindusinberre** [comment]
@interrogator @witlox could you please check this on a dodgy internet connection and close if you're happy?

**Comment by interrogator** [comment]
Not an easy thing to test, but closing due to the code being added. Will reopen something if problems aren't fixed by the timeout change...
