### ISSUE TITLE
notebook scrolling with long text

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#25]
notebook scrolls up when give something in.

**Comment by martindusinberre** [comment]
Yes, this arose in the test: when the player inputs a lot of text in the notebook, it automatically scrolls up. It seems to be a problem with the amount of text inputted (e.g. a long article abstract or a long input from the player).

**Comment by christian-bernet** [comment]
Estimate 2 hours

**Comment by christian-bernet** [comment]
it is only on firefox

**Comment by martindusinberre** [comment]
Does that mean it's a bug or a settings problem?

**Comment by christian-bernet** [comment]
tested on Chrome and Firefox. But bug can't be reproduced.

**Comment by christian-bernet** [comment]
reproduced on chrome and firefox

**Comment by martindusinberre** [comment]
Basically: copy and paste a long text into the textExercise component on 2.1.3. Then try to input more text at the bottom of the long text input. You'll see that you keep getting scrolled away from where your cursor is / where you want to input text.

**Comment by lfeine** [comment]
This is still happening to me on Firefox 69.0 (OSX). Fixed on my Chrome install though.

**Comment by christian-bernet** [comment]
Yes, it is still there fro Firefox on mac osx!

**Comment by martindusinberre** [comment]
Still also happening for Safari in Mac OSX (12.1.2)

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/c70b860aa9f20614a9ba8ba936c19568f3f49a68 clipboard paste also handled

**Comment by christian-bernet** [comment]
if you hit enter, the fist line is cut off.
![image](https://user-images.githubusercontent.com/41006947/65138035-9bcde180-da0a-11e9-870b-eac7150d38f7.png)

instead of
![image](https://user-images.githubusercontent.com/41006947/65138068-a8ead080-da0a-11e9-9e40-dc852ca8858b.png)

Or if you have a long input field it cut on line off at the end.

But it is working on Chrome, Safari and Firefox now.

**Comment by martindusinberre** [comment]
I've been testing this (on safari) this morning. It's much better than before. Basically, if the player keeps writing an input, there is no problem at all with scrolling.
The problem *only* occurs when the player copy and pastes a big amount of text into the notebook (sometimes the game asks the player to do this). In this situation, the scrolling function is broken: it's very difficult to add any text *after* the pasted text.

**Comment by christian-bernet** [comment]
I tried it also with long text and it works perfect.
![image](https://user-images.githubusercontent.com/41006947/65225939-4951fb00-dac6-11e9-8030-50d98c6d292b.png)


Can you give me a more detailed description of how to reproduce this bug.
Thanks.

**Comment by martindusinberre** [comment]
Perhaps it's a problem with safari? @interrogator would you mind trying to see if it's just a browser problem or a bug? Please see my comment from this morning. Thanks

**Comment by interrogator** [comment]
Scroll when typing and pasting both work OK for me on Linux/Firefox.

**Comment by martindusinberre** [comment]
OK, great. May be a problem with safari or something else. I'm going to close it for now.
