### ISSUE TITLE
Navigation of notebook broken

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#26]
if you have a lot of entries the last navigation points are not reachable.

**Comment by martindusinberre** [comment]
This may be related: at some points not all the notebookEntry titles are visible in the notebook's Table of Contents (the black section).

**Comment by christian-bernet** [comment]
Estimate 2 hours

**Comment by zlaxi** [comment]
Bug was related to firefox browser, commit is :
https://github.com/uzh/marugoto-frontend/commit/7caba3b2f4f0f3cd18efdc0f9fe7bc78b5282bfb

**Comment by christian-bernet** [comment]
that works now.
I checked that.

You can now scroll now also in the firefox.

**Comment by christian-bernet** [comment]
Navigation is cutted of since the newest change!

![image](https://user-images.githubusercontent.com/41006947/64529432-288de680-d30b-11e9-8a8e-dac52abfee4e.png)
