### ISSUE TITLE
Email inbox small feature change

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#29]
When a player receives an email, the email display on the right-hand side of the page includes the button "Respond to E-mail". (This button is also at the end of the displayed email.) In both cases, can we change this simply to "Reply"?

**Comment by christian-bernet** [comment]
Estimate 1 houres

**Comment by interrogator** [comment]
This took less than 30 seconds. Wonder why never done? Changed here

https://github.com/uzh/marugoto-frontend/commit/7435c775edf58d4431067921bcd06308f7a18de8

**Comment by christian-bernet** [comment]
Sorry, that was forgotten.
