### ISSUE TITLE
Notebook problem with "add new note"

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#30]
The players are confused by the fact that when they "add new note" to a particular notebook page, and then return to the main page, and then open the notebook again and try to "add new note", they cannot do so.
I think there are two solutions to this:
- **either** the button "add new note" should no longer display when the student opens a new note, so that it's clear that they have to return to the input field they were previously using
- **or** we should add the button "Save Notebook Input", which the player will close before they leave the notebook; and then, when they return to the notebook (still on the same page), the "add new note" button actually opens an entirely new text field, with its own time stamp.

**Comment by christian-bernet** [comment]
Estimate 2 houres

**Comment by martindusinberre** [comment]
I don't think this is a necessity at this point--it's a desirable, perhaps for post-2020.
