### ISSUE TITLE
swiping back / using back button in browser

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#32]
The players were frustrated that when they swiped back a page on their touchpad, or used the browser back button, they were take to the front page of the game. Is there any kind of pop-up functionality we can add to warn the player that they are effectively about to exit the game?

**Comment by christian-bernet** [comment]
@zlaxi what is here possible?
estimate: 4 houres

**Comment by christian-bernet** [comment]
do nothing if you click on "back"
