### ISSUE TITLE
Remove gender choice in first sign-in

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#33]
For avoidance of difficult gender issue debates, I think we should remove the gender choice (male/female) from the player's first sign-in. Once this is done, I'll remove the user.gender references in the json files, and just use the first+last name combination instead.

**Comment by christian-bernet** [comment]
estimate: 4 houres

**Comment by martindusinberre** [comment]
This is connected to #48 (according to Pim's input today)
