### ISSUE TITLE
Ability to input textExercise *and* see zoomed image simultaneously

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#34]
This is a high-priority request from the players: at the moment, when they have a textExercise (e.g. 2.4.1.3.1.2, or when it repeats as 2.4.3.1.1.2, 2.4.4.1.1.2 and 2.4.5.1.1.2), they are unable to read the handwriting in the unzoomed image. So they use the image zoom functionality. But then they are unable to input the textExercise without first closing the image zoom. One player responded by taking a photo of the zoomed image and then using the photo (on her phone) to complete the textExercise. 
Is there any way we can have zoomed image and some kind of text input (textExercise, dateExercise etc) on the same page?

**Comment by christian-bernet** [comment]
estimate: 4 houres

**Comment by christian-bernet** [comment]
add zoom functionality also to the image in content.

**Comment by martindusinberre** [comment]
We have decided to make this a non-priority for the current project. The work-around is to have transcription exercises with big imageComponents (ie column width 8 and offset 2), and then the textExercise component directly below them. I will adjust PlantationLives accordingly after the demo topic is finished.
