### ISSUE TITLE
Page transition not possible on 2.4.5.1.1.2

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#37]
This happened to me in my testing on Friday at 2.4.5.1.1.2, and it happened to a player on Monday also on the same page (2.4.5.1.1.2): the "continue" button becomes invisible on this page, and there's no way to continue the game (going back to ".../games" and then clicking on "Continue" for existing games doesn't work).

**Comment by christian-bernet** [comment]
estimate: 2 houres

**Comment by christian-bernet** [comment]
related to https://github.com/uzh/marugoto/issues/46

**Comment by christian-bernet** [comment]
This should be not possible any more, because of the changes of https://github.com/uzh/marugoto/issues/46

**Comment by martindusinberre** [comment]
I'll close this because we are testing #46

**Comment by Helena-LiT** [comment]
This still does not work. I can not trasition off this page. It only affects page transitions from HSA, when you visit it on day 5 so I compared the json here with the other HSA pages. It seems that there is a little mistake in the transition json on that page:
`{
  "id": null,
  "from": null,
  "to": "chapter4/2.4.5.1.1.3/page.json",
  "buttonText": "Continue",
  "time": {
    "time": 0
  },
  "money": {
    "amount": 0
  },
  "criteria": [
    {
      "pageCriteria": null,
      "exerciseCriteria": null,
      "mailCriteria": null,
      "affectedExercise": null,
      "affectedPage": null,
      "affectedDialogResponse": "chapter4/2.4.4.1.1.2/dialogResponse1.json",
      "affectedMail": null
    }
  ]
}`

I think  "affectedDialogResponse" should be "chapter4/2.4.**5**.1.1.2/dialogResponse1.json"

**Comment by martindusinberre** [comment]
Great, good spot, Lena. I've corrected the pageTransition1.json for 2.4.5.1.1.2. Could you test it again? I've created a temporary shortcut to 2.4.5.1.1.1 to speed things up... If it seems solved, then please close the issue.

**Comment by Helena-LiT** [comment]
It works now.
