### ISSUE TITLE
FAQ on front page in case of browser pop-up blocking problems etc

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#42]
This from Lena: it relates to #36 and #40: can we add a tab for FAQs on the front page in case a player (particularly in Firefox) comes across problems in playing the game?

**Comment by interrogator** [comment]
So main page should have `FAQ`, `Twitter` and `GitHub` links at the top somewhere? Any others?

**Comment by martindusinberre** [comment]
Main page should have FAQ as one of the tabs down the left hand side, I think. Twitter and Github links at the top, I would suggest. Or under the signature, "The LiT Team, UZH"?

**Comment by interrogator** [comment]
OK decision time for this one, I've added the About tab, can either add another for FAQ or have FAQ inside About. @martindusinberre you can decide!

**Comment by martindusinberre** [comment]
@interrogator if it's easy to add a new tab for FAQ, I would: I think "About" and "FAQ" are two different things. We will need to populate FAQ as and when we get feedback, and identify certain problems (e.g. try not to play on X browser); the "about" is more about future potential collaborations / how we've set up the game for open access. I think that means six tabs in total: hope that's not too much? Thanks, Martin

**Comment by interrogator** [comment]
Doesn't take long to add a tab, but yeah, more than six starts seeming like a lot, so hopefully this is all for now. Will add now.

**Comment by martindusinberre** [comment]
Great. Take down reviews for the time being if you want, as it's empty; but hopefully we coudl get some endorsements there before April, as in a book publication... Will leave this to you--perhaps an empty tab looks naff? Can you hide it easily?

**Comment by interrogator** [comment]
They can be hidden if really necessary, but trying to populate them is nicer!

FAQ tab is now coded, but we need actual FAQ text for it as well, right now it just has dummy text.

I would agree with hiding Reviews for the time being if we aren't expecting any to roll in. But we can do it in later issue, it is not related to this and not so urgent...

Visually yeah, 6 tabs is already a lot, should be max.

**Comment by martindusinberre** [comment]
@interrogator One key question which we should put in FAQ (please edit to clarify as you see fit):
Question: Is Lives in Transit a commercial or for-profit project?
Answer: No, Lives in Transit is entirely non-commercial, not-for-profit. It has been developed as part of a publicly-funded academic research project led by the University of Zurich (see "Partners" tab).

**Comment by interrogator** [comment]
Good. Note that @lfeine is now also able to edit HTML for these pages, she is welcome to help out on this one. need 5 or 6 questions to justify the section i suppose! :grin:

**Comment by martindusinberre** [comment]
Another one:
Question: Where is the line between fact and fiction in Lives in Transit?
Answer: (a) All of the documents (primary and secondary sources) that you see in Lives in Transit are real. So are the archives and public institutions in which you collect those sources. (b) However, your "home" institutions, including your university and local museums, are fictional, as are all the characters that appear in the game. All of the interactions you have in the game are also fictional and the product of the authors' imagination. Thus, in your interactions with fictional characters, any resemblance to actual persons, living or dead, events, or locales is entirely coincidental.

**Comment by lfeine** [comment]
We can include the FAQ part of the privacy agreement in the FAQ page as well, since it's just rephrasing things it already states in the proper agreement.

**Comment by interrogator** [comment]
A couple more and I will make into HTML and release. One question will be about license and copyright stuff.

**Comment by martindusinberre** [comment]
@interrogator @lfeine @Helena-LiT 
OK, the questions as of Monday evening (11th November):

[NB: please make sure this is the first question; otherwise, I leave the order to you] 
Question: Is Lives in Transit a commercial or for-profit project?
Answer: No, Lives in Transit is entirely non-commercial, not-for-profit. It has been developed as part of a publicly-funded academic research project led by the University of Zurich (see "Partners" tab).

Question: Where is the line between fact and fiction in Lives in Transit?
Answer: (a) All of the documents (primary and secondary sources) that you see in Lives in Transit are real. So are the archives and public institutions in which you collect those sources. (b) However, your "home" institutions, including your university and local museums, are fictional, as are all the characters that appear in the game. All of the interactions you have in the game are also fictional and the product of the authors' imagination. Thus, in your interactions with fictional characters, any resemblance to actual persons, living or dead, events, or locales is entirely coincidental.

Question: What is the software behind Lives in Transit?
Answer: The software programme has been custom-built for this project by our external partners, and is completely open source. The programme is called "Marugoto" (meaning "the whole" in Japanese). For information about how you can contribute to Lives in Transit, please see the "About" tab.

Question: [@lfeine about pop-ups]

Question: How does Lives in Transit protect my privacy?
Answer: Please refer to the "Data use agreement" on Lives in Transit's log-in page.

Question: [@interrogator about HTML and release/copyright stuff--as in an earlier comment in this issue]

**Comment by lfeine** [comment]
I've added the questions to the FAQ tab, let me know if there should be more questions/any changed.
Related commit: https://github.com/uzh/marugoto-frontend/commit/3abc0f357812d55bd891068daa39001ca945156b

**Comment by martindusinberre** [comment]
As discussed on Wednesday 20th, this issue is actually closed.
