### ISSUE TITLE
Data protection clarity (and text for frontpage)

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#45]
Can we have absolute clarity on what text we need to include on the frontpage for data protection (and whether we need to be more explicit about email storage protections, pseudonyms etc)?

**Comment by martindusinberre** [comment]
Leyla will talk to her colleagues at DLF about this with particular reference to whether student input in MOOCs (or Adfontes) count as "private data". Ideally, she would be able to come back to us with a draft text that could go on the game's frontpage (in one of the tabs)

**Comment by lfeine** [comment]
I asked about the data privacy and Anita said the deciding factor is where our data is stored. If it's all within the university/switzerland, it shouldn't be a problem, but we should probably include some sort of user agreement that specifies how long the data is stored and what it's used for. If the data is stored with a third party outside of switzerland, we'd have to make a contract with them. Anita could help with that though.

**Comment by martindusinberre** [comment]
Pim, can you please check where our data will be stored so that Leyla can get back to DLF? Thanks, Martin

**Comment by witlox** [comment]
data will only be stored `in system`, as long as the system is hosted in Switzerland, the data will reside in Switzerland.

**Comment by martindusinberre** [comment]
Now that we're clear from Pim that the data is stored in Switzerland, then it's time to deal with this from your previous comment: "we should probably include some sort of user agreement that specifies how long the data is stored and what it's used for". @witlox can you let Leyla know this, and then @lfeine can you please go to Anita in DLF and see if they have some kind of template text we can use for the LiT frontpage? Thanks

**Comment by interrogator** [comment]
@lfeine I can add it, but don't know what the text is. Please add it here, ideally as HTML but plain text with links at bottom OK too

**Comment by lfeine** [comment]
Sorry, I've sent it directly to Pim! Here's the text (it's a txt file but contained within should be valid HTML I've written up)
[TOS.txt](https://github.com/uzh/marugoto/files/3783083/TOS.txt)

**Comment by interrogator** [comment]
OK, these terms have been added to the site, so closing
