### ISSUE TITLE
Add a Home button, in place of Back functionality

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#47]
Back functionality is being disabled, to stop the user exiting the game by mistake.

Instead, we should add some kind of link to the mainpage from within the game, either saying `Marugoto` or `Home`. Seems like this can just be done in pure HTML.

**Comment by christian-bernet** [comment]
We will solve this with:
- disable the back functionality of the browser
- add an icon at the right down corner to get to the "Your games" Screen

**Comment by christian-bernet** [comment]
please add this Icon
![image](https://user-images.githubusercontent.com/41006947/64600829-19b33c80-d3bc-11e9-91e9-7a267aad32b1.png)

<svg width="32" height="29" xmlns="http://www.w3.org/2000/svg"><path d="M16 12.2l4.6 3.45-1.2 1.6-2.4-1.8V29H5v-2h10V15.45l-2.4 1.8-1.2-1.6L16 12.2zM16 .22L26.975 9H27v.018l4.625 3.7-1.25 1.563L27 11.579 27 23h-8v-2h6V9.98l-9-7.2-9 7.2V21h6v2H5V11.58l-3.375 2.7-1.25-1.561L5 9.019 5 9h.024L16 .22z" fill="#2F3133" fill-rule="nonzero"/></svg>

**Comment by christian-bernet** [comment]
<svg width="32" height="29" xmlns="http://www.w3.org/2000/svg"><path d="M16 12.2l4.6 3.45-1.2 1.6-2.4-1.8V29H5v-2h10V15.45l-2.4 1.8-1.2-1.6L16 12.2zM16 .22L26.975 9H27v.018l4.625 3.7-1.25 1.563L27 11.579 27 23h-8v-2h6V9.98l-9-7.2-9 7.2V21h6v2H5V11.58l-3.375 2.7-1.25-1.561L5 9.019 5 9h.024L16 .22z" fill="#2F3133" fill-rule="nonzero"/></svg>

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/c83ba7c1482fdf9c13f363c8bf5fa6efb9fb627e

**Comment by christian-bernet** [comment]
only icon is placed. back functionality not touched.

**Comment by martindusinberre** [comment]
I'm happy with this.
