### ISSUE TITLE
GitHub and Twitter links on main page

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#49]
Users need to be able to give feedback. It makes sense that they can either Tweet at us, or make GitHub issues. So, two buttons in the HTML, plus adding a `Contributing` section to this README.

**Comment by interrogator** [comment]
I can write the contributing section.

**Comment by martindusinberre** [comment]
See our comments also in #42

**Comment by christian-bernet** [comment]
We place the links left to the Disclaimer:
Git Twitter Disclamer
![image](https://user-images.githubusercontent.com/41006947/65148689-01c56380-da21-11e9-94b3-83b439fed954.png)

Please add the links here in this issue. Thanks.

**Comment by martindusinberre** [comment]
Here is the Twitter link:
https://twitter.com/TransitLives
@interrogator can you please add the github link when you have it and then reassign to Christian?

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/15ba98e3457438b66bdfdaa3f21a4d466ef2eb6d

**Comment by christian-bernet** [comment]
ok. done.

**Comment by martindusinberre** [comment]
Great, will close this now.
