### ISSUE TITLE
Notebook PDF is not working on the test system

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#52]
From the frontend on the test system there is a wrong url called.
It has /resources/ before, which is wrong.
https://marugoto.s3it.uzh.ch/resources/api/notebook/pdf/current

Please change it.

**Comment by christian-bernet** [comment]
on Safari we can not download notebook pdf in the game

**Comment by christian-bernet** [comment]
If we have an image in the pdf, then we get an exception org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation

**Comment by christian-bernet** [comment]
OK. It is working now.

@martindusinberre from now the notebook pdf and the zip from from the game screen will work.
Please try. :)

**Comment by martindusinberre** [comment]
Yes, I was able to download the notebook PDF mid-game just now using the download icon. Thanks!
