### ISSUE TITLE
Section layout messed up when notebook is open and dialog pops up

### ISSUE THREAD

**Issue by nemtish** [uzh/marugoto#53]
<img width="1436" alt="Screenshot 2019-09-11 at 10 36 39" src="https://user-images.githubusercontent.com/19348068/64682252-74fb3280-d481-11e9-9dda-26ee293fe6e7.png">

**Comment by christian-bernet** [comment]
this is the Split screen bug we have: https://github.com/uzh/marugoto/issues/5

**Comment by nemtish** [comment]
alright, this is first time I am seeing it :)..

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/6aecf7c8c44879e89fc834e99a30293890373af7

**Comment by christian-bernet** [comment]
ok. that one is definitely fixed. I will close this issue.
