### ISSUE TITLE
Fix supervise class screen

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#55]
**Date selector**
If you change the date in frontend backend is not updated correctly.
Please fix frontend component.
![image](https://user-images.githubusercontent.com/41006947/64781537-608f6680-d563-11e9-8bc4-b701ecb893a1.png)

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/22cfcce8d27949b7eb61af15ab9a690f5b174e98

**Comment by christian-bernet** [comment]
Selected date in date picker is no stored in backend.
If you set a date and come back afterwards to the same calls nothing is saved and also not the stored date is show.

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/d7d8761603d48432fc2cd13bf69e65a0d17ad2ce

**Comment by christian-bernet** [comment]
ok. that works.

**Comment by martindusinberre** [comment]
@Helena-LiT This is an important one. Could you please check it carefully and close if you're happy? Thanks.

**Comment by Helena-LiT** [comment]
All these features seem to work correctly: the date picker, editing class name and description; the link works; downloading the student notebook works (also when the game is unfinished). The only thing that startled me is that the students are not directed to any particular topic but are allowed to choose to play whatever they want. This seems a bit unusual for a class setting. However, the teacher can instruct the students to pick a particular storyline, so no big deal.
If you try to use the link you generated as a teacher to play the game (with the same account) you get a warning that you can's supervise and play at the same time. Which is how it is supposed to be. All fine as far as I can tell.
