### ISSUE TITLE
Date picker widget does not display correctly 

### ISSUE THREAD

**Issue by lfeine** [uzh/marugoto#56]
Depending on screen size, the date picker widget does not display all numbers, or displays them outside of the container. Right now the picker only functions correctly between 1110 and 1124 window width. Tested on Chrome and Firefox.

<img width="445" alt="Screenshot 2019-09-13 at 15 43 43" src="https://user-images.githubusercontent.com/54706676/64868380-825e1b80-d63f-11e9-9721-06f349629545.png">
<img width="820" alt="Screenshot 2019-09-13 at 15 47 40" src="https://user-images.githubusercontent.com/54706676/64868386-87bb6600-d63f-11e9-959a-c5d7e875b3f8.png">
<img width="1253" alt="Screenshot 2019-09-13 at 15 48 06" src="https://user-images.githubusercontent.com/54706676/64868395-8d18b080-d63f-11e9-97c1-acbf0e036701.png">

**Comment by lfeine** [comment]
We've decided the best solution is just to remove the date picker widget entirely. The input field for the date stays the same.

**Comment by christian-bernet** [comment]
@zlaxi remove it for the component date exercise!

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/d7d8761603d48432fc2cd13bf69e65a0d17ad2ce

**Comment by christian-bernet** [comment]
update is not done when it is date 1.1.2019 for example. But that is also right.

**Comment by christian-bernet** [comment]
ok. fixed in backend with c3f54edf868182989eb3f278ec51e83b492c626a

**Comment by martindusinberre** [comment]
@lfeine could you check this please? Please close if you're happy.

**Comment by lfeine** [comment]
Date picker is removed correctly, however the input fields are misaligned. This makes it unclear which label belongs to which input field. 
This seems to occur on all window width available on my laptop, as well as on Chrome and Firefox.
<img width="614" alt="Screenshot 2019-09-27 at 10 08 02" src="https://user-images.githubusercontent.com/54706676/65753204-c9074780-e10e-11e9-8969-e9ffe888ad27.png">

**Comment by christian-bernet** [comment]
this is on the pages 2.4.3.1.2.2 (or 2.4.4.1.2.2 or 2.4.5.1.2.2)

**Comment by christian-bernet** [comment]
@zlaxi can you please check that.
As I see there are 10 columns used and 1 offset at the left. So that should be ok from the content side.

**Comment by christian-bernet** [comment]
added label to DateExercise: Backend a7570527

**Comment by christian-bernet** [comment]
@interrogator can you please change the validator
the dateExercise needs now an attribute "label" which can be null or a string.

Example for dateExercise
{
  "id": null,
  "numberOfColumns": 3,
  "offsetColumns": 0,
  "renderOrder": 10,
  "showInNotebook": true,
  "showInNotebookAt": "pageExit",
  "page": null,
  "label": "Please enter the date:",
  "solution": {
    "correctDate": "03.01.1886"
  }
}

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/795a1ad5182d7efb56cb072f6fa731e7434d8a7a

**Comment by christian-bernet** [comment]
OK. that is fixed now.
@martindusinberre please use the new label of the dateExercise to add a description for a dateExercise and not an other TextComponent.

![image](https://user-images.githubusercontent.com/41006947/67195630-9133ad00-f3f9-11e9-8b18-2265aab51ca4.png)

**Comment by martindusinberre** [comment]
Great, got it. Many thanks.
