### ISSUE TITLE
Order of images in Notebook PDF appendix

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#61]
The appendix looks great and seems to display images with multiple jpgs. Thanks!
But please look at this PDF (generated in the middle of chapter 4): the images in the appendix appear in a random order, rather than in the order that I played the game. The Strong painting is first, which is fine, but then should come the contract (which incorrectly has the title "Chronicling America general notes", but I think that is a content/input error which I can fix in json), and then the HSA documents. 
[Martin Dusinberre-2.pdf](https://github.com/uzh/marugoto/files/3630348/Martin.Dusinberre-2.pdf)
So: can the order of the appendix reflect the order the images were acquired in the game?

**Comment by nemtish** [comment]
should work with: https://github.com/uzh/marugoto/commit/262bc7f4f42bb842b8ed5c8ccb0776f1d99e33b7

**Comment by christian-bernet** [comment]
OK. fixed.

**Comment by martindusinberre** [comment]
@lfeine Could you please check this and then close it? Thanks, Martin

**Comment by lfeine** [comment]
Tested, they are in the right order in my PDF as far as I can tell.
[Leyla Feiner.pdf](https://github.com/uzh/marugoto/files/3746216/Leyla.Feiner.pdf)
