### ISSUE TITLE
Simplifying functionality at known weak spots

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#65]
As discussed 23/9/19, Chapter 1 of Plantation Lives contains some fairly advanced functionality that seems to be a bit error prone when multiple things are going on (esp. timed dialog while using notebook/email, or something equally complex). The features are all nice, and in an ideal world we have them working in the game. But by current cost/benefit analysis, getting these features working flawlessly is less important than the game being stable and playable. User won't miss much if an incoming phone call happens after hitting 'Continue'. Having it work as imagined could be a v2 milestone?

So, it'd be nice if for now we just simplified the chapter 1 and 2 content a little bit, so that the game is more playable, though slightly less dynamic. A big part of this relates to timed actions (see #64 for more general thoughts on these).

@martindusinberre please note, a nice thing about git: you can always revert back to the advanced functionality that's currently there, once the bugs are definitively fixed. No need to backup the current version of the game, it's all remembered, and if/when the time comes, I'll show you how to use git to bring back the old content.

**Comment by martindusinberre** [comment]
Good, I'll work on this after we've got a trailer, and will make sure that the trailer is less complex in its first pages. Thanks, Danny.
