### ISSUE TITLE
Test crazy user behaviour

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#67]
Often, it is hard to manually test your code, because you tend to use it in the way it was designed to be used. However, actual users will do all kinds of things you don't expect.

Recently I found that during chapter 1, if I clicked various buttons as quickly as possible, I could get myself into weird states like split screen, from which it was difficult to recover. Reproducing this isn't always easy, but I'm going to try to reproduce consistently.

I believe the most realistic thing to do about this issue is to hope that it is fixed while addressin related matters, like #5 , #24, #64,  #65 and so on.

The other thing we can do, rather than 'fix', is add an extra button during beta/trailer release for bug reporting (see #66), which tells the user that bugs are possible during beta phase.

I know @witlox doesn't always like non-programmers writing issues to devs on GitHub, but I see no issue with this, our users are all smart, and having humanists use tools like git(hub) is part of an outcome of the project. I hereby volunteer to screen any incoming issues from users on our repo :smile:

**Comment by martindusinberre** [comment]
I'm going to close for the time being because I (hope) the issue isn't a problem for the time being...
