### ISSUE TITLE
Feedback so far on Trailer (in OurTestTopic)

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#69]
@witlox @interrogator @Helena-LiT @lfeine I'm ready for a bit of feedback on the trailer as you have it so far. It's incomplete, but before I spend a lot more time building it, would be glad for feedback on the feel, the variety of exercises etc. All comments most welcome!
(Please imagine playing it at trailer speed, rather than going through as quickly as possible to the end!)

**Comment by interrogator** [comment]
One thing I felt wasn't clarified, what happens to the text I wrote that was submitted at game end? Is that actually going to be manually reviewed?! I wasn't sure how the transition to the full game will work --- did my choices here actually affect my next game?!

**Comment by martindusinberre** [comment]
@interrogator text will be saved to Notebook (if you're talking about the GLAMM job application). But you won't know that until you download your notebook (or look at it on the very last page).
Whether it will be reviewed or not, and how it affects the later part of the game--that's the whole insecurity that you *should* feel! You don't know what the museum director makes of your text; you don't know whether, even if he likes it, you'll get the job. And so, hopefully, you might want to come back in the spring and find out... :)

**Comment by interrogator** [comment]
This makes sense in terms of how we are supposed to feel etc. But I wonder if people should, in this case, be able to go back and update their answer? Otherwise, expect 50% of responses to be `lol it don't matter wat i type here` ...

**Comment by martindusinberre** [comment]
@interrogator Yes, exactly: that's a more general problem we have with trying to convince the player that their input means something. I tried to address that with the extra sentence I added at the end of 1.1.2, but that (a) is probably going to be ignored and (b) is only relevant for players playing in a class. 
I've got no idea what to do about it! Going back isn't really an option if we want simulation to be the key element of the game: in real life, you can't go back and rewrite a job interview test if you don't take it seriously the first time round. I'm inclined to think we should keep simulation--ie you can't go back--as the key feature of the game. But would there be any other way of making the player feel more invested in his/her input which didn't involve them having the option of going back and rewriting? Or we could add a bit of storyline which effectively gives the player a second chance: the director gives some feedback, for example; he points out something in the photo; he asks for you to edit your input. Which would work fine but adds to the playing time of the demo, and also doesn't necessarily deal with players who will write "lol" in any case.
It may be this is something we could throw out to demo players as well for feedback? So far, we have been amused in testing to see how seriously people did take these tasks, and many others which we didn't even set them (e.g. several people who've played the demo say that they wrote an angry email to the library protesting their fines), so I wonder if we just have to take a risk: those who will play it seriously will play it seriously; those who will write "lol" we should figure are not going to take it seriously?

**Comment by Helena-LiT** [comment]
@martindusinberre You could also use some preformulated answers of the kind you have in the questionary at the beginning. There could be even some "lol" nonsense answers to indicate the player does not take this seriously. I would still have an input field, but the general attitude towards the exercise could be then inferred from that selection.

**Comment by Helena-LiT** [comment]
I would also like to note that Professor Witles changes gender mid-game. Is that on purpose? 

> 1.1.1 "You also wonder about the professor's conclusion that “our skills have not been sufficiently utilized.” What skills does she mean? (Witles=she)
1.1.5 You remember that Professor Witles made a comment about situational perspectives being a metaphor for academic research. He evidently meant this as a joke, for he had laughed loudly afterwards." (Witles=he)

**Comment by Helena-LiT** [comment]
As I have mentioned before, I still have the impression that in the trailer we seem to have a student who is unusually preoccupied with his/her Prefessors remarks, jokes and aphorisms:

> 1.1.1 "**You also wonder about the professor's conclusion** that “our skills have not been sufficiently utilized.” What skills does she mean?

> 1.1.2 **you remember an article by Lara Putnam that Professor Witles made you read** for class last semester. There was a sentence in it which stuck with you: “Things happen in archives and libraries and on the way to them.”

> 1.1.5 **You remember that Professor Witles made a comment about situational perspectives** being a metaphor for academic research. He evidently meant this as a joke, for he had laughed loudly afterwards."

**Comment by martindusinberre** [comment]
@Helena-LiT Like the pre-defined answers idea--will try to think how the content could change on that.
On the gender: the first professor (1.1.1.) refers to the prof in the video. I can try to name her, but wondered if that would complicate things. I also assume that if the player has watched the video, that comment (about "sufficiently utilized") is the very last thing they've seen before they transition to 1.1.1, so it should be fresh in the mind.
On the student's preoccupation: yes, that's a good observation. Any solutions to it?!

**Comment by Helena-LiT** [comment]
@martindusinberre 
> On the student's preoccupation: yes, that's a good observation. Any solutions to it?!

Lats time we spoke about this I have already suggested a few things but it really depends on what the function of these "memories" is supposed to be. Are they there to characterize Witles as a person or do they give direction to the research? If the latter is the case, then they could come from any source: 

> you remember an article by Lara Putnam that Professor Witles made you read for class last semester. There was a sentence in it which stuck with you: “Things happen in archives and libraries and on the way to them.”

The player could leaf through his/her old notes in an old notebook and notice the Putnam quote written some time ago; a reference can be found on the margin of a page in a book you have just opened.

>  You remember that Professor Witles made a comment about situational perspectives being a metaphor for academic research. He evidently meant this as a joke, for he had laughed loudly afterwards."

Someone other than Witles could give you a hint or make a joke...

> but you reap what you invest (as Professor Witles is also fond of saying)

anyone could have said that: mother, father, grandmother, the bank manager you are meeting on Thursday...

**Comment by martindusinberre** [comment]
Thanks all: I've incorporated these suggestions as much as I can.
