### ISSUE TITLE
Email notification behind imageComponent

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#71]
In 1.1.3 and 1.1.4 of OurTestTopic, an email notification comes in while the player is on the page. Currently, the notification comes *behind* the imageComponent (which is wide here--8 columns). Shouldn't the email notification come *in front of* the image?

**Comment by nemtish** [comment]
Notification should always be in front otherwise doesn't make sense..Someone will check this

**Comment by christian-bernet** [comment]
![image](https://user-images.githubusercontent.com/41006947/66759521-b3c94180-eea0-11e9-8d21-61fa8a65da66.png)

@zlaxi please fix that, its on page Tsuneno from Echigo Province of the "Our Test Topic"

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/ee8bcdd4b279b0c7252e531ca8ba75d5ac9488c5

**Comment by christian-bernet** [comment]
ok.

**Comment by martindusinberre** [comment]
@lfeine please could you check this and then close it? (It's only relevant at this point to the OurTestTopic. Thanks, Martin

**Comment by lfeine** [comment]
Tested on Firefox and Chrome, fix successful.
