### ISSUE TITLE
Italics in a textComponent don't become italics in the PDF notebook download

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#73]
The example here is 1.1.7.2.3 (OurTestTopic). textComponent2 is saved to Notebook--and that functionality all works well. But when the notebook is downloaded, the italics (Warren, *Ah Ku and Karayuki-san*) don't appear as italics but as normal text with asterisks either side of them.

**Comment by christian-bernet** [comment]
Use this to convert the textnode;
https://itextpdf.com/en/resources/books/itext-7-converting-html-pdf-pdfhtml/chapter-1-hello-html-pdf

**Comment by christian-bernet** [comment]
Reviewed new Version:
- HandlebarHelper: line 177 (renderUploadExercise): upload-name is wrong generated: if fixed that in the old version. please fix it!

**Comment by nemtish** [comment]
fix - https://github.com/uzh/marugoto/commit/1b719c15fc23cf4931014dd9b7137d7b0ed97926

**Comment by christian-bernet** [comment]
Ok. both fixed.
And also italic (markup content) works in pdf.

@martindusinberre this is fixed.
We had to rewrite the pdf generation for that. So please review the notebook pdf again completely, so that we are sure that everything is on the right place.

**Comment by lfeine** [comment]
The italics issue is fixed. I'm currently still reviewing the PDF for any new issues, I will make a separate issue for any new problems that crop up.
