### ISSUE TITLE
textComponents saved to notebook and downloaded as PDF

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#74]
When a textComponent saves to notebook (e.g. OurTestTopic 1.1.7.2.1), the layout is fine. When the notebook is downloaded as a PDF, the text is both left *and* right-justified. Is it possible for the textComponent only to be *left*-justified? 
(for reference, please see the way that the players' "Add note" inputs are saved to the PDF: they are only left-justified, too).
And, assuming this is possible, is it a lot of work to implement?

**Comment by nemtish** [comment]
Hi @martindusinberre, this is easy fix..Text in PDF will be left aligned

**Comment by christian-bernet** [comment]
done with a1ca83968504bfd2bf41a3960f106b220e89aebc

**Comment by christian-bernet** [comment]
done with: a1ca8396

**Comment by martindusinberre** [comment]
@lfeine Please could you check this and close the issue? Thanks, Martin

**Comment by lfeine** [comment]
Tested, text is now left-aligned.
