### ISSUE TITLE
Host all fonts on our servers

### ISSUE THREAD

**Issue by lfeine** [uzh/marugoto#75]
Due to privacy concerns, it would be better to host all of our fonts on our servers rather than accessing them through google fonts.
We've checked and the fonts we currently use should all be open and available.

**Comment by martindusinberre** [comment]
@lfeine Great. Can you assign this to someone or is this something you can do yourself?

**Comment by martindusinberre** [comment]
@lfeine This still hasn't been assigned, so I've kicked it back to you and included Danny, as probably he will be in charge of making sure the fonts are on the servers.

**Comment by interrogator** [comment]
Yes, it is for me and maybe @witlox to do. We discussed, and this is necessary due to Swiss law.
