### ISSUE TITLE
user.firstName etc functionality not working on one page

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#76]
This is a strange one: in the OurTestTopic, user.firstName and user.lastName work well everywhere *except* on 1.1.7.1.1 testComponent1.json. 
To solve the problem, I tried copy-pasting them in from a json file where they were working fine, but this hasn't changed the frontend view. 
Is this a bug?

**Comment by martindusinberre** [comment]
OK, got it.

**Comment by interrogator** [comment]
@martindusinberre closing seems we know what happened and how to avoid. One day this should make it into content creation FAQs though!

**Comment by martindusinberre** [comment]
@interrogator Yes, we have a good workaround. 
Strategic question: I have been keeping enhancement/lowest issues open, just so we know what is still desirable in the future. Do you want me to close them, but then revisit them after spring 2020? Up to you--you have more experience in github etiquette... :)

**Comment by interrogator** [comment]
I think it's nice to be able to close all your issues as they are 'complete for now'. It isn't hard to reopen next year if need be.
