### ISSUE TITLE
hyperlinks not working in imageComponents or videoComponents captions

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#77]
This arises from my successfully embedding a hyperlink in 1.1.7.1.3 and 1.1.7.2.6 respectively (the link is to our Twitter page). In other words, the embedded hyperlink works fine in a textComponent json file.
But when I use exactly the same string to embed a hyperlink in the caption of an imageComponent or a videoComponent, it doesn't work. Please check OurTestTopic 1.1.3 and 1.1.4 to see what I mean.

**Comment by christian-bernet** [comment]
In caption of imageComponent and videoComponent it is not possible to place text with markdown.
This is only possible for the TextComponent.

**Comment by martindusinberre** [comment]
OK, got it.

**Comment by martindusinberre** [comment]
@witlox @interrogator Guys, how easy is it for you to fix this? It would make our captions look a lot sharper if we could include hyperlinks. But it might be related also to #89 ?
It's not a priority but if it's an easy fix, then that would be good to know.

**Comment by interrogator** [comment]
We can look into it, should be fixable!

**Comment by interrogator** [comment]
We started looking into this today. Pim has just had to go, but a solution is on the way...we think we may as well allow you to add markdown/HTML for any text-like field, eh?

**Comment by martindusinberre** [comment]
Perfect--that would be great. Thanks, M

**Comment by interrogator** [comment]
Done in https://github.com/uzh/marugoto-frontend/commit/bc74f6cc578aabc17193d0a9dc3c26ba4024838e . Was not very hard, just need a `<vue-markdown>` element. We can probably do this for more types of text input, maybe @martindusinberre can tell us if there are any places he would particularly like to be able to add markdown/HTML-enabled text

**Comment by interrogator** [comment]
(Will make a new issue if need be)
