### ISSUE TITLE
Zoom function in imageComponent with multiple jpg images

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#8]
For images with multiple jpg files: you can scroll through the images fine on the page; you can also zoom the first jpg file. But you can't zoom into any of the later jpg files within the image.

**Comment by christian-bernet** [comment]
(-) There is no way to zoom 2nd image
(-) User should be able to slide left/ right when image is zoomed
(-) Check image component not being changed after transition from 2.4.3.1.1.5 to 2.4.3.2

**Comment by christian-bernet** [comment]
test it with Demo-Topic chapter 2 page 2

**Comment by martindusinberre** [comment]
OK, I'll look as soon as the importer is working...

**Comment by christian-bernet** [comment]
ok. tested on Demo-Topic and  from 2.4.3.1.1.5 to 2.4.3.2.
1392745 on frontend master

**Comment by martindusinberre** [comment]
I've tested it on 2.4.1.3.1.4 and it's looking great.
