### ISSUE TITLE
numberOfColumns for textComponent

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#80]
In 1.0.0 textComponent1.json, I have set 
"numberOfColumns": 10,
  "offsetColumns": 1,
But on the frontend, this component has the same margin as textComponent2.json, which has a different setting:
"numberOfColumns": 8,
  "offsetColumns": 2,
textComponents3 and 4 have numberOfColumns = 8 as well, as do checkboxExercise1,2 and 3

This is the same problem for 1.1.7.2.3 textComponent1.json, which has:
"numberOfColumns": 10,
  "offsetColumns": 1,
But the frontent display seems to be only 8 columns with an offset of 2. 

Have I made a mistake somewhere? Or is not possible to have textComponents which have 10 columns?

**Comment by martindusinberre** [comment]
Here's the screenshot for 1.0.0 with the margins the same even though the numberOfColumns is different
<img width="1168" alt="Screen Shot 2019-10-24 at 12 23 48" src="https://user-images.githubusercontent.com/53183999/67476954-54fe8780-f659-11e9-8231-bc6210b78c5f.png">

**Comment by zlaxi** [comment]
https://github.com/uzh/marugoto-frontend/commit/a28913630376f859a42ee778b635d6b2d0542699

**Comment by interrogator** [comment]
So it looks like we should redeploy test environment soon and check if this worked?

**Comment by christian-bernet** [comment]
My plan was to review it before pushing it to master.
But now it's on master already.
At the moment https://marugoto.s3it.uzh.ch/login is not working.
I will review it tomorrow.

**Comment by interrogator** [comment]
We added logout options today, bugs are likely to do with that, so don't
stress.

**Comment by martindusinberre** [comment]
@interrogator so is this fixed or not? If so, please close.

**Comment by christian-bernet** [comment]
that is done and now also reviewed.
I will close this now.
