### ISSUE TITLE
Initial multiple choice questions --- in character or not?

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#85]
When doing the initial multiple choice in trailer, I had no idea if I was answering honestly or as some character. Can this be clarified in the text? I didn't know if user experience survey or character building...

**Comment by martindusinberre** [comment]
Yes, I'm working on this with Leyla now and also shortly with a psychologist colleague! Will hope to rewrite by Thursday (am on the train all day to Portugal tomorrow)

**Comment by martindusinberre** [comment]
Hope we have got closer to dealing with this problem with the latest push.
