### ISSUE TITLE
manual import of Trailer: Defining Work

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#86]
@witlox @interrogator I've just pushed a set of changes on Atom/git. Please do a manual import now/whenever you have time and then please close this issue. Thanks, Martin

**Comment by martindusinberre** [comment]
Hi @witlox @interrogator I have just pushed some more changes, so would be grateful if you could do a manual import on Wednesday so that I can play again on Thursday. Thanks, Martin

**Comment by interrogator** [comment]
This is old.
