### ISSUE TITLE
Deleting 'open games'?

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#87]
I have dozens, and would love to be able to hit an X, confirm, and they are gone forever...

**Comment by martindusinberre** [comment]
@christian-bernet Is this possible? I can't remember whether this was something we discussed. Certainly, as I remember, it's possible to wipe them from the backend. But perhaps not from the frontend?

**Comment by christian-bernet** [comment]
That is not possible. Also wipe them from the backend is not possible.

**Comment by interrogator** [comment]
Add `x` button to `display=none` the row and store which games are 'shown' in db? Surely others have bumped into issue of having many many open games and no idea which is which

**Comment by martindusinberre** [comment]
@interrogator Is this something that you could change fairly easily?

**Comment by interrogator** [comment]
To do it comprehensively is a fair bit of work ... we could easily add a button to hide in frontend, but they would come back next session unless we store the 'hidden' info in the database. so it means a database update which is a fair bit of work. I suggest we don't worry about this for now, but if there is a future database change, we can also explore deleting/hiding old/dead games.

Can reprioritise if users have this feedback, problem looks worse for devs because we are constantly messing with the app I think.

**Comment by martindusinberre** [comment]
Yes, I agree--we are definitely not the normal player profile here. Let's keep it as a desired enhancement--I've relabelled it as such, to make it consistent with other similar issues. Many thanks, Martin
