### ISSUE TITLE
Money calculator mistake

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#9]
(again, from July 22:) I was just playing 2.4.3.1.1.5, where I had 301EUR. When I transitioned into 2.4.3.2, the game should have reduced my 301 EUR by 25 EUR (-25.0). But now I'm on 2.4.3.2, my money amount is simply shown as -25 EUR. So the calculator isn't quite working as planned.

**Comment by christian-bernet** [comment]
I tried it now on the test-system and it worked correctly.

**Comment by martindusinberre** [comment]
This is still occurring: I'm in chapter 4 having taken the shortcut "good/decent money". This gave me 700 EUR, then down to 501 EUR (after page 2.4.1.1a--this is correct); then I couldn't see whether it had added 200 EUR (I went to 2.4.1.3.4.2D) because of the split screen bug; but after choosing HSA at 2.4.2.2 and then playing through to 2.4.3.1.1.5, the problem occurred. That is, in transitioning from 2.4.3.1.1.5 to 2.4.3.2, I should have had 25EUR deducted from my money. But when I land on 2.4.3.2, my money counter says "-25EUR" instead of the correct amount (which should be 676 EUR). In other words, the money deduction on the 2.4.3.1.1.5/pageTransition1.json isn't working, because it doesn't remember the previous total. 
This is not the only place the problem occurs--it's just one example.
