### ISSUE TITLE
Minor thread 🤘🗒️

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#90]
Collection of small bugs and corrections as I see them, for quickfixing

- [x] Standardise quotation marks, bold and italics
- [x] Do we have a quote-like environment for suggested citation? cannot use `<code>` because of hyperlinks
- [x] Change download notebook icon to 'download' text, to match 'continue'
~~Style Your Games more like welcome page~~
- [x] href underlining in welcome pages
- [x] bibtex citation

Please add to list any other little frontendy things as you see them, will check off as they are patched.

**Comment by lfeine** [comment]
(replying here from  #83 )
I'm really not familiar with bibtex, unfortunately. If it can wait about a week, I can look into it if you want.

**Comment by interrogator** [comment]
No it's OK @lfeine , I'm sure I will have time at some point to do it! Just thought maybe you'd already be a bibtex person :)

**Comment by martindusinberre** [comment]
- [ ] On the "Partners" tab, please have the Hyperlinks open in a new tab.

- [ ] On the "Create LiT account" part of the front page, please add question-marks to the end of each verification question.

**Comment by martindusinberre** [comment]
- [ ] On the "Your Games" page: can you please make the font for the second paragraph ("Remember that...") the same as for the first? More significantly: do we want to give this information away? We discussed this quite a lot a year or so ago and were keen not to give the player too much information about their ability to revisit the choices they made. Don't you think they could work it out simply if they had the information: "Remember that you can always return here to start a new game, even if you have another in progress."
@interrogator @Helena-LiT what do you think?

**Comment by martindusinberre** [comment]
- [ ] On the "Topic Selection" page: I'd prefer if we keep all mention of Marugoto away from the frontend as much as possible. Please change the second sentence to: "In the meantime, you can get a playable preview of one topic currently under development by working through a short extract. The topic is called **Defining Work**."

- [ ] On the "Topic Selection" page: please make sure the second paragraph has the same font size as the first.

**Comment by interrogator** [comment]
Thanks, these are all easy to do.

Quick note however @martindusinberre, you asked me to go use some initiative and flesh out paragraphs with new text where I can. But so far, even the smallest of these changes has met with (totally understandable) resistance, generally based on a discussion that was had before I arrived on the project. I can't divine the outcomes of these discussions, and am pretty sure that most things I add in the future will meet the same fate (it has happened about 4 times since Friday). So for now, I'm happy to give back the 'artistic licence', and restrict the stuff I do without checking with you prior to spelling, grammar, formatting. I can add text that you write (e.g. for About/FAQ etc), and also to collect my opinions on changes I would like, such as my issue the name 'topic' vs 'game' and so on ...  but coming up with content and then reverting it is not a good use of time :nerd_face:

**Comment by interrogator** [comment]
Everything ticked off in this thread is in frontend master branch btw

**Comment by martindusinberre** [comment]
@interrogator great. 
About the editing process more generally: Re "your games": mine is a question, not a shut-down. If you think the second paragraph you added should stay even in light of the question I asked, then please just answer why you think so, and leave it in. That's why I also asked @Helena-LiT for her opinion.
Re. "topic selection": this is something you and I discussed on rocketchat last Friday, where I explicitly said that we wanted to keep mention of "marugoto" away from the player except in the "about" tab. That was a decision. If you think it's wrong, please reopen a discussion but don't just make the change as if we never had a discussion.
More generally about your perception that I'm shutting your ideas down: this thread is not the place for you to air that perception. We have a meeting tomorrow at 10am--let's talk about it then.

**Comment by interrogator** [comment]
I don't think it's 'shutting down', don't worry --- it's just that it turns out that you guys have thought through a lot of the stuff I find myself thinking through, it ends up duplicating efforts, reverting changes, and so on. But yeah we can find a solution to the thing tomorrow if you still think it is necessary to have me trying to create content for the main page. I just think focussing on edits, in addition to coding, might be a better use of time at present. To discuss.

**Comment by martindusinberre** [comment]
Great, good plan. Definitely sounds like a good idea to avoid duplicatio. See you tomorrow, M

**Comment by martindusinberre** [comment]
@

- [ ] In the "Partners" tab, please add the following sentence at the end of paragraph 2 (after "...offered feedback on the game since 2016." The sentence is: 
"The core LiT team during development has been: Martin Dusinberre, Helena Jaskov and Leyla Feiner (UZH Department of History), Pim Witlox and Danny McDonald (UZH S3IT), Ramun Riklin (Ansich), and Christian Bernet, Joachim Hummel (Vitamin2) and Bastian Heer (formerly Vitamin2)."

**Comment by interrogator** [comment]
Can do if need be, but might be a good practice run for @lfeine ?

**Comment by lfeine** [comment]
Good idea, I'll do that this weekend then.

**Comment by martindusinberre** [comment]
@interrogator 

- [ ] Change the time stamp settings in "Your games". This is because when I exited a game halfway through just now, "Open Games" recorded my unfinished game as being played on 7 December, not 7 November!

- [ ] For the time stamp in the Notebook, can we set it to Central European Time? At the moment it's on Greenwich Mean Time. Not a major problem if it's a lot of work, though.

**Comment by martindusinberre** [comment]
- [ ] Can @interrogator suggest in which tab on the front page we add the following sentence (or something similar)? "Every effort has been made to check copyright for the images appearing in Lives in Transit, and to provide bibliographic links. Please contact the LiT Team if you spot any inadvertent errors in acknowledgement."

**Comment by interrogator** [comment]
![same-size](https://user-images.githubusercontent.com/10471132/68471580-cbd17e00-021e-11ea-96ca-ed27ab6a6dd9.png)

**Comment by interrogator** [comment]
Just a note on the above --- there are classes like `lead`/`lead-text` which one would think should be used for the first paragraph of text on pages like this. But such classes make the paragraph bigger, and it looks nasty when there is a second smaller paragraph underneath. Best solution is to simply never use the `lead` type classes when styling these content blocks. The above is how it looks with no lead classes and with a `<br/>` between paragraphs. This info may help @lfeine in formatting various text blocks.

Note, we're trying not to mess with the existing CSS, because doing that will cause weird stuff to happen inside the game. For example, `<a href=...` elements won't get styled with underlines because of the existing CSS. If you want underlines, do `<a class="underlined" href=...`. i.e., If you need anything extra in terms of CSS, best way is always to create new classes, rather than modifying what is already there.

**Comment by interrogator** [comment]
>     * [ ]  Can @interrogator suggest in which tab on the front page we add the following sentence (or something similar)? "Every effort has been made to check copyright for the images appearing in Lives in Transit, and to provide bibliographic links. Please contact the LiT Team if you spot any inadvertent errors in acknowledgement."

One solution, we could have it in FAQ, for a question like `How is Lives in Transit licensed?`? Some other stuff could go in there as well... @martindusinberre how does that sit with you? Helps flesh out FAQ section, which we need right now

**Comment by interrogator** [comment]
* [ ] align the `Supervise group game` and `Sign out` buttons to the right of the div, and prevent them breaking into two rows on a small screen @witlox .

**Comment by martindusinberre** [comment]
@interrogator great, please put that sentence in FAQ then, along with the licencing stuff.
And who was giving me grief for US english the other day ? :) "licensing"...

**Comment by interrogator** [comment]
@martindusinberre on the select topic screen, can we change:

* [ ] `Preview this topic` -> `Launch`

It isn't a preview (anymore)...

**Comment by martindusinberre** [comment]
@interrogator Yes, good idea. Thanks.

**Comment by interrogator** [comment]
* [ ] Remove German-style noun capitalisation (i.e. `Forgot Password` -> `Forgot password`)

**Comment by martindusinberre** [comment]
- [ ] implement the revised verification questions from MD's edits on #97 

- [ ] In the "Citing LiT" tab, the example just *before* the .bib format should now read:
Dusinberre, Martin, Helena Jaskov, Pim Witlox, Daniel McDonald and Leyla Feiner, "Defining Work", ... [and then as is]
[NB we'll change this according to the topic: where Lena is the lead author, her name will come first]

- [ ] (I don't know whether this is easy, and it's definitely not a priority) In the "Terms of Service", the section headings cling to the previous paragraph, while a big gap appears between those headings and the upcoming paragraph to which they pertain. In Word, one would say that the paragraph spacing "after" is too big and "before" is too small. Can the layout be fixed to address this?

- [ ] In "ToS" 2 and 2a, there are several different fonts at work. It settles down after paragraph 3. Is it possible to make the font in 2 and 2a consistent with the rest of the page?

- [ ] In "ToS" 2, the sentence *after* "Last name" is missing a verb: currently it reads: We process this information in order for the game to your `character` in the correct context.
--> please change to: We process this information in order for the game to react to your "character" in the correct context.

- [ ] In "Terms of Service", point 5, please change "purpose" to "purposes". 

- [ ] "ToS" point 12, the email address should have a lower-case "g", --> globalhistory@hist.uzh.ch  And please correct this where the email appears elsewhere

**Comment by martindusinberre** [comment]
@interrogator  Sorry, I now realise we've managed to overlook explaining "Marugoto" on the "About" tab. My suggestion (please edit/rewrite/restructure as you see fit):

- [ ] A sentence right under "About" but before "bug bounty": Lives in Transit is run through a custom-built programme called "Marugoto" (meaning "the whole" in Japanese).

- [ ] If a sentence like this goes in, then I'd suggest one change to the first sentence of "Creating your own content", namely: It's possible to create your own playable topics, simply by writing JSON files that Marugoto can import and serve to Lives in Transit.

**Comment by martindusinberre** [comment]
- [ ] On "Your Games", there needs to be a space between "Transit" and "Home"

**Comment by martindusinberre** [comment]
- [ ] Minor issue (not urgent before demo launch) but just for the sake of consistency: if we're taking out bolds and replacing them with italics, then we should do that for the "Select a topic" page, too...

**Comment by interrogator** [comment]
> @interrogator
> 
>     * [ ]  Change the time stamp settings in "Your games". This is because when I exited a game halfway through just now, "Open Games" recorded my unfinished game as being played on 7 December, not 7 November!
> 
>     * [ ]  For the time stamp in the Notebook, can we set it to Central European Time? At the moment it's on Greenwich Mean Time. Not a major problem if it's a lot of work, though.

This gets its own issue, so closing here

**Comment by interrogator** [comment]
Closing this long thread. Will make a new one. Great job @martindusinberre @lfeine
