### ISSUE TITLE
Frontend display doesn't match order of pageTransition files

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#92]
This is a screenshot of 1.0.2 in the Trailer/demo.
<img width="1021" alt="Screen Shot 2019-11-04 at 20 47 04" src="https://user-images.githubusercontent.com/53183999/68152700-76f2e680-ff44-11e9-89e8-261bff8b09d6.png">
But the pageTransition.json files are numbered differently. 
1.0.2/pageTransition4.json, for example, is "...people in positions of responsibility..."
It's quite important to me that this particular button text is the last on this page, as it sets up the content for the next page. Can anyone explain why the pageTransition4 button is displaying as the second option on the frontend?
Thanks, Martin

**Comment by interrogator** [comment]
Looks like a bug on @christian-bernet 's side. Assuming he can fix a lot faster than we can.

**Comment by martindusinberre** [comment]
@christian-bernet Please could you let me know when this could be fixed? It's actually more urgent than #28 at the moment as it affects the playable demo, which we plan to make live on Tuesday 12th November.

**Comment by christian-bernet** [comment]
@martindusinberre I started yesterday and will finish it hopefully today or tomorrow.

**Comment by christian-bernet** [comment]
done with d36b6f87
