### ISSUE TITLE
PDF Export: Long links linebreak incorrectly

### ISSUE THREAD

**Issue by lfeine** [uzh/marugoto#94]
When exporting a notebook entry with a long link to PDF, the link stops linebreaking after the first line and gets cut off at the edge of the page. 
<img width="746" alt="Screenshot 2019-11-06 at 14 18 04" src="https://user-images.githubusercontent.com/54706676/68301446-44f69700-00a0-11ea-8913-dd1996febcd9.png">

**Comment by nemtish** [comment]
fix https://github.com/uzh/marugoto/commit/f89080757da7182484bdbbf63821816b4fd4f027

**Comment by christian-bernet** [comment]
fixed with cf84fb9c

**Comment by interrogator** [comment]
Nice solution! Much better than line breaking.
