### ISSUE TITLE
Validation questions for new log-in

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#97]
As requested by Pim: the questions shouldn't be so easy as for a computer to understand them.
@witlox or @interrogator could you cut and paste the current questions here as I'm not able to see them on acrion?

**Comment by interrogator** [comment]
Currently we have:

```

let questions = {
    "What colour is the sky": "blue",
    "What colour is an apple": "green",
    "What colour is the sea": "blue",
    "What colour does the sun have": "yellow",
    "What colour does the traffic light have when you have to stop": "red",
    "What colour does growing foliage have": "green",
    "What colour does egg yolk have": "yellow",
    "What is the colour of a clown's nose": "red",
    "What colour does tree bark have": "brown",
    "What's the colour of snow": "white",
    "What is the colour of an orange": "orange",
    "What is the main color of the UN flag": "blue",
    "What is the colour of coal": "black",
    "In which city is the Eiffel Tower located": "paris",
    "In which city is the Big Ben located": "london",
    "In which city is the Taj Mahal located": "agra",
    "In which city is the Sagra de Familia located": "barcelona",
    "In which city is the Acropolis located": "athens",
    "In which country is the Sydney Opera House located": "australia",
    "In which US state is the Golden Gate Bridge located": "california"
};
```

Anybody brave enough can simply add questions to: https://github.com/witlox/acrion/blob/master/data.js

**Comment by martindusinberre** [comment]
@witlox Hope you can just copy and paste these corrections? Then I'll think of more questions

"What colour is the clear sky": "blue",
"What colour is a clementine": "orange",
"What colour is the sea": "blue",
"What is generally the colour of the moon": "white",
"What is the colour of a traffic light when you have to stop": "red",
"What colour is healthy grass": "green",
"What colour is egg yolk": "yellow",
"What is the colour of a clown's nose": "red",
"What is the colour of tree bark": "brown",
"What's the colour of snow": "white",
"What is the main colour of the UN flag": "blue",
"What is the colour of coal": "black",
"In which city is the Eiffel Tower located": "Paris",
"In which city is the Big Ben located": "London",
"In which country is the Taj Mahal located": "India",
"In which city is the Acropolis located": "Athens",
"In which country is the Sydney Opera House located": "Australia",
"In which US state is the Golden Gate Bridge located": "California"

Plus
"What is the colour of the night sky": "black"
"What colour is milk": "white"
"In which country is British Columbia": "Canada"
"In which country is New South Wales": "Australia"
"In which country are the pyramids": "Egypt"
"What is the main colour in the Swiss flag": "red"
"What colour is mercury": "silver"
"What is the main colour of the EU flag": "blue"

Hope this is a useful start?

**Comment by interrogator** [comment]
OK two Sydney questions!? Cash me outside @martindusinberre @witlox

**Comment by martindusinberre** [comment]
:) 
@witlox how many more do you want?

**Comment by interrogator** [comment]
Update, I added the damn question marks to existing question. Let's get a few more in there and release it!?

**Comment by lfeine** [comment]
I've tried to come up with some additional question formats, let me know if they work for your purposes before I add them (and their variations) @witlox 

`"What animal catches mice": "cat",
    "What is the taste of lemons":"sour",
    "What does fire feel like":"hot",
    "Where do deer live":"forest",`

**Comment by witlox** [comment]
@lfeine we've just created a new version. Thanks for the questions, we'll try them for the next round.
