### ISSUE TITLE
add production container and define test container for frontend

### ISSUE THREAD

**Issue by witlox** [uzh/marugoto#98]
currently the .env.production is used for test and prod, which won't work, because the paths are hardcoded. split off and create own containers for prod(:latest) and test(:test)

**Comment by interrogator** [comment]
Let's make sure we have all this organised the right way from the beginning, eh?

Currently after_success builds and pushes with two different tags:

https://github.com/uzh/marugoto/blob/master/.travis.yml

Is this correct, and is this how we want to do it?
